config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("var_log_recetas.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("ingredient/", include("var_log_recetas.ingredient.urls")),
    path("recipe/", include("var_log_recetas.recipe.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
    if "silk" in settings.INSTALLED_APPS:
        import silk.urls

        urlpatterns += [path("silk/", include(silk.urls, namespace="silk"))]

var_log_recetas/ingredient/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #     path('', views.index, name='index'),
    path("", views.IngredientListView.as_view(), name="ingredient_list"),
    path("add/", views.IngredientAddView.as_view(), name="ingredient_add"),
    path(
        "add/modal/",
        views.IngredientModalAddView.as_view(),
        name="ingredient_add_modal",
    ),
    path(
        "add/modal/submit/",
        views.IngredientModalAddView.as_view(partial=True),
        name="ingredient_add_modal_submit",
    ),
    path(
        "<int:ingredient_id>/",
        views.IngredientUpdateView.as_view(),
        name="ingredient_update",
    ),
    path("unit/", views.MeasureUnitListView.as_view(), name="unit_list"),
    path("unit/add/", views.MeasureUnitAddView.as_view(), name="unit_add"),
    path(
        "unit_group/", views.MeasureUnitGroupListView.as_view(), name="unit_group_list"
    ),
    path(
        "unit_group/add/",
        views.MeasureUnitGroupAddView.as_view(),
        name="unit_group_add",
    ),
    path(
        "unit_group/<int:unit_group_id>/",
        views.MeasureUnitGroupUpdateView.as_view(),
        name="unit_group_update",
    ),
]

var_log_recetas/recipe/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# pylint: disable=line-too-long
from __future__ import absolute_import, unicode_literals

import logging

from django.urls import path

from . import views

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name


urlpatterns = [
    path("", views.RecipeListView.as_view(), name="recipe_home"),
    path("add/", views.RecipeCreateView.as_view(), name="recipe_add"),
    path("export/", views.recipe_export_all, name="recipe_export_all"),
    path("<int:recipe_id>/", views.recipe_view, name="recipe_view"),
    path("<int:recipe_id>/edit/", views.RecipeEditView.as_view(), name="recipe_edit"),
    path(
        "<int:recipe_id>/parts/", views.RecipePartsView.as_view(), name="recipe_parts"
    ),
    path(
        "<int:recipe_id>/parts/add/",
        views.RecipeAddPartView.as_view(),
        name="recipe_parts_add",
    ),
    path("<int:recipe_id>/export/", views.recipe_export, name="recipe_export"),
    path(
        "part/<int:subrecipe_id>/",
        views.SubRecipeDetailView.as_view(),
        name="subrecipe_edit",
    ),
    path(
        "part/<int:subrecipe_id>/rename/",
        views.SubRecipeRenameView.as_view(),
        name="subrecipe_rename",
    ),
    path(
        "part/<int:subrecipe_id>/ingredient_add/",
        views.subrecipe_edit_ingredient_add,
        name="subrecipe_edit_ingredient_add",
    ),
    path(
        "part/<int:subrecipe_id>/ingredient_delete/",
        views.subrecipe_edit_ingredient_delete,
        name="subrecipe_edit_ingredient_delete",
    ),
    path(
        "part/<int:subrecipe_id>/ingredients/",
        views.subrecipe_edit_ingredients,
        name="subrecipe_edit_ingredients",
    ),
    path(
        "part/<int:subrecipe_id>/step_add/",
        views.subrecipe_edit_step_add,
        name="subrecipe_edit_step_add",
    ),
    path(
        "part/<int:subrecipe_id>/step_delete/",
        views.subrecipe_edit_step_delete,
        name="subrecipe_edit_step_delete",
    ),
    path(
        "part/<int:subrecipe_id>/step_move_up/",
        views.subrecipe_edit_step_move_up,
        name="subrecipe_edit_step_move_up",
    ),
    path(
        "part/<int:subrecipe_id>/step_move_down/",
        views.subrecipe_edit_step_move_down,
        name="subrecipe_edit_step_move_down",
    ),
    path(
        "part/<int:subrecipe_id>/steps/",
        views.subrecipe_edit_steps,
        name="subrecipe_edit_steps",
    ),
]

var_log_recetas/users/urls.py
from django.urls import path

from var_log_recetas.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

var_log_recetas/ingredient/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext as _
from django.views.generic import FormView, ListView, UpdateView

from var_log_recetas.utils.views import GenericFormMixin

from .forms import (
    IngredientForm,
    IngredientModalForm,
    MeasureUnitForm,
    MeasureUnitGroupForm,
)
from .models import Ingredient, MeasureUnit, MeasureUnitGroup


class IngredientListView(ListView):
    model = Ingredient


class IngredientAddView(GenericFormMixin, FormView):
    form_class = IngredientForm
    title = _("Agregar ingrediente")

    def form_valid(self, form):
        form.save()
        return redirect("ingredient_list")


class IngredientModalAddView(FormView):
    form_class = IngredientModalForm
    template_name = "modal_form_base.html"
    partial = False

    def form_valid(self, form):
        form.save()
        return HttpResponse("1")

    def get_context_data(self, *args, **kwargs):
        data = super(IngredientModalAddView, self).get_context_data(*args, **kwargs)
        data["partial"] = self.partial
        data["id"] = "ingredient-create"
        data["title"] = _("Agregar ingrediente")
        return data


class IngredientUpdateView(GenericFormMixin, UpdateView):
    model = Ingredient
    form_class = IngredientForm
    pk_url_kwarg = "ingredient_id"
    success_url = reverse_lazy("ingredient_list")
    title = _("Modificar ingrediente")


class MeasureUnitListView(ListView):
    model = MeasureUnit


class MeasureUnitAddView(GenericFormMixin, FormView):
    form_class = MeasureUnitForm
    title = _("Agregar unidad")

    def form_valid(self, form):
        form.save()
        return redirect("unit_list")


class MeasureUnitGroupListView(ListView):
    model = MeasureUnitGroup


class MeasureUnitGroupAddView(GenericFormMixin, FormView):
    form_class = MeasureUnitGroupForm
    title = _("Agregar grupo de unidades")

    def form_valid(self, form):
        form.save()
        return redirect("unit_group_list")


class MeasureUnitGroupUpdateView(GenericFormMixin, UpdateView):
    model = MeasureUnitGroup
    form_class = MeasureUnitGroupForm
    pk_url_kwarg = "unit_group_id"
    success_url = reverse_lazy("unit_group_list")
    title = _("Modificar grupo de unidades")

var_log_recetas/recipe/views.py
import datetime
import json
import logging

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.text import slugify
from django.views.generic import DetailView, FormView, ListView, RedirectView

from var_log_recetas.ingredient.models import MeasureUnit
from var_log_recetas.utils.views import has_get_models, has_models

from .forms import (
    MeasuredIngredientForm,
    RecipeAddForm,
    StepForm,
    SubRecipeForm,
    SubRecipeSelectForm,
)
from .models import MeasuredIngredient, Recipe, Step, SubRecipe

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name


def _render_json_error(err, *_args, **_kwargs):
    return HttpResponse(json.dumps({"success": False, "error": str(err)}))


class RecipeListView(ListView):
    model = Recipe


class RecipeCreateView(FormView):
    form_class = RecipeAddForm
    template_name = "recipe/recipe_form.html"

    def form_valid(self, form):
        form.save()
        return redirect("recipe_edit", form.instance.id)


class RecipeEditView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        recipe = get_object_or_404(Recipe, pk=kwargs["recipe_id"])
        try:
            subrecipe_id = self.request.GET["subrecipe"]
            subrecipe = recipe.subrecipe_set.get(id=subrecipe_id)
        except (KeyError, SubRecipe.DoesNotExist):
            subrecipe = recipe.subrecipe_set.first() or recipe.subrecipe_set.create(
                title="la receta"
            )
        return reverse("subrecipe_edit", kwargs=dict(subrecipe_id=subrecipe.id))


class RecipePartsView(DetailView):
    model = Recipe
    pk_url_kwarg = "recipe_id"
    template_name = "recipe/recipe_parts.html"


class RecipeAddPartView(FormView):
    form_class = SubRecipeForm
    template_name = "generic/form.html"

    def get_form(self, form_class):
        recipe = get_object_or_404(Recipe, id=self.kwargs.get("recipe_id"))
        subrecipe = SubRecipe(recipe=recipe)
        return form_class(instance=subrecipe, **self.get_form_kwargs())

    def form_valid(self, form):
        form.save()
        return redirect("recipe_parts", form.instance.recipe.id)


class SubRecipeRenameView(FormView):
    form_class = SubRecipeForm
    template_name = "generic/form.html"

    def get_form(self, form_class):
        subrecipe = get_object_or_404(SubRecipe, id=self.kwargs.get("subrecipe_id"))
        return form_class(instance=subrecipe, **self.get_form_kwargs())

    def form_valid(self, form):
        form.save()
        return redirect("recipe_parts", form.instance.recipe.id)


class SubRecipeDetailView(DetailView):
    model = SubRecipe
    pk_url_kwarg = "subrecipe_id"

    def get_context_data(self, *args, **kwargs):
        context = super(SubRecipeDetailView, self).get_context_data(*args, **kwargs)
        if self.object.recipe.subrecipe_set.count() > 1:
            context["subrecipe_select_form"] = SubRecipeSelectForm(
                self.object.recipe, initial=dict(subrecipe=self.object.id),
            )
        context["recipe"] = self.object.recipe
        return context


def home(request):
    return render(
        request, "recipe/home.html", {"recipes": Recipe.objects.all().order_by("id")}
    )


def recipe_detail(request, recipe):
    return render(request, "recipe/recipe_detail.html", {"recipe": recipe})


@has_models
def recipe_edit(request, recipe):
    return render(request, "recipe/recipe_edit.html", {"recipe": recipe})


@has_models
def subrecipe_edit(request, subrecipe):
    return render(
        request,
        "recipe/subrecipe_edit.html",
        {"recipe": subrecipe.recipe, "subrecipe": subrecipe},
    )


def _get_object_or_none(model, model_pk):
    try:
        return model.objects.get(pk=model_pk)
    except (model.DoesNotExist, ValueError):
        return None


@has_models
def subrecipe_edit_ingredient_add(request, subrecipe):
    instance = MeasuredIngredient(subrecipe=subrecipe)
    if request.method == "POST":
        form = MeasuredIngredientForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponse("1")
    else:
        unit_id = request.GET.get("unit", None)
        unit = _get_object_or_none(MeasureUnit, unit_id)
        form = MeasuredIngredientForm(
            instance=instance,
            initial={
                "ingredient_name": request.GET.get("ingredient_name"),
                "amount": request.GET.get("amount", None),
                "unit": unit,
            },
        )
    form.helper.form_id = "ingredient-add-form"
    return render(request, "recipe/recipe_edit/ingredient_add.html", {"form": form})


@has_models
def subrecipe_edit_ingredient_delete(
    request, subrecipe
):  # pylint: disable=invalid-name
    error = None
    try:
        ingredient_id = request.GET["ingredient_id"]
    except KeyError:
        error = "Missing ingredient_id"
    else:
        try:
            ingredient = subrecipe.measuredingredient_set.get(pk=ingredient_id)
        except MeasuredIngredient.DoesNotExist:
            error = "Ingredient does not exist"
        else:
            ingredient.delete()

    return HttpResponse(json.dumps({"success": not error, "error": error}))


@has_models
def subrecipe_edit_ingredients(request, subrecipe):
    return render(
        request,
        "recipe/recipe_edit/ingredients.html",
        {"measured_ingredients": subrecipe.measuredingredient_set.all()},
    )


@has_models
def subrecipe_edit_step_add(request, subrecipe):
    instance = Step(subrecipe=subrecipe)
    if request.method == "POST":
        form = StepForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponse("1")
    else:
        step_id = request.GET.get("step", None)
        step = _get_object_or_none(Step, step_id)
        unit_id = request.GET.get("unit", None)
        unit = _get_object_or_none(MeasureUnit, unit_id)
        form = StepForm(
            instance=instance,
            initial={
                "step": step,
                "amount": request.GET.get("amount", None),
                "unit": unit,
            },
        )
    form.helper.form_id = "step-add-form"
    return render(request, "layout/crispyform.html", {"form": form})


@has_get_models("step", on_error=_render_json_error)
def subrecipe_edit_step_delete(
    _request, subrecipe, step
):  # pylint: disable=unused-argument
    step.delete()
    return HttpResponse(json.dumps({"success": True}))


@has_models
def subrecipe_edit_steps(request, subrecipe):
    return render(
        request, "recipe/recipe_edit/steps.html", {"steps": subrecipe.step_set.all()}
    )


def recipe_add(request):
    recipe = Recipe()
    if request.method == "POST":
        form = RecipeAddForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect("recipe_recipe_edit", recipe.id)
    else:
        form = RecipeAddForm(instance=recipe)
    return render(request, "recipe/recipe_add.html", {"form": form})


def _swap_steps(step, ostep):
    step.position, ostep.position = ostep.position, step.position
    step.save()
    ostep.save()


@has_get_models("step", on_error=_render_json_error)
def subrecipe_edit_step_move_up(_request, subrecipe, step):
    error = None
    previous_step = (
        subrecipe.step_set.filter(position__lt=step.position)
        .order_by("-position")
        .first()
    )
    if previous_step is None:
        error = "There is no previous step"
    else:
        _swap_steps(step, previous_step)
    return HttpResponse(json.dumps({"success": not error, "error": error}))


@has_get_models("step", on_error=_render_json_error)
def subrecipe_edit_step_move_down(_request, subrecipe, step):
    error = None
    next_step = (
        subrecipe.step_set.filter(position__gt=step.position)
        .order_by("position")
        .first()
    )
    if next_step is None:
        error = "There is no next step"
    else:
        _swap_steps(step, next_step)
    return HttpResponse(json.dumps({"success": not error, "error": error}))


@has_models
def recipe_export(_request, recipe):
    filename = "receta-{}-{}.json".format(recipe.id, slugify(recipe.title))
    response = HttpResponse(
        json.dumps(recipe.as_json(), indent=1), content_type="application/json"
    )
    response["Content-Disposition"] = "attachment; filename={}".format(filename)
    return response


def recipe_export_all(_request):
    output = {}
    for recipe in Recipe.objects.all():
        output[recipe.id] = recipe.as_json()
    now = datetime.datetime.now()
    filename = "recetas-{}.json".format(now.strftime("%Y-%m-%d.%H.%M.%S"))
    response = HttpResponse(
        json.dumps(output, indent=1, sort_keys=True), content_type="application/json"
    )
    response["Content-Disposition"] = "attachment; filename={}".format(filename)
    return response


def recipe_view(_request, _recipe):
    pass

var_log_recetas/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}/var/log/recetas{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/var_log_recetas.css' %}" rel="stylesheet">
    <link href="{% static 'css/sweet-alert.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">/var/log/recetas</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="recipeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% trans "Recetas" %}
              </a>
              <div class="dropdown-menu" aria-labelledby="recipeDropdown">
                <a class="dropdown-item" href="{% url "recipe_home" %}" >{% trans "Recetas" %}</a>
                <a class="dropdown-item" href="{% url "recipe_add" %}">{% trans "Nueva Receta" %}</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="ingredientDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% trans "Ingredientes" %}
              </a>
              <div class="dropdown-menu" aria-labelledby="ingredientDropdown">
                <a class="dropdown-item" href="{% url "ingredient_list" %}" >{% trans "Ingredientes" %}</a>
                <a class="dropdown-item" href="{% url "ingredient_add" %}">{% trans "Nuevo ingrediente" %}</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="unitDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% trans "Unidades" %}
              </a>
              <div class="dropdown-menu" aria-labelledby="unitDropdown">
                <a class="dropdown-item" href="{% url "unit_list" %}" >{% trans "Unidades" %}</a>
                <a class="dropdown-item" href="{% url "unit_add" %}">{% trans "Nueva unidad" %}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url "unit_group_list" %}" >{% trans "Grupos de unidades" %}</a>
                <a class="dropdown-item" href="{% url "unit_group_add" %}">{% trans "Nuevo grupo de unidades" %}</a>
              </div>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      <h1>
        {% block page_title %}Example Base Template{% endblock page_title %}
        <div class="pull-right">{% block page_buttons %}{% endblock page_buttons %}</div></h1>

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-1.11.1.js'%}"></script>
    <script src="{% static 'js/jquery.form.3.51.0.js'%}"></script>
    <script src="{% static 'js/sweet-alert.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/var_log_recetas.js' %}"></script>
    <script src="{% static 'js/modal_utils.js' %}"></script>

    {% block extra_js %}
    {% endblock extra_js %}

    {% endblock javascript %}
  </body>
</html>

var_log_recetas/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}
{% block page_title %}Home{% endblock page_title %}

{% block content %}
<ul class="nav nav-pills nav-stacked">
  <li><a href="{% url "recipe_home" %}">Recetas</a></li>
  <li><a href="{% url "ingredient_list" %}">Ingredientes</a></li>
  <li><a href="{% url "unit_list" %}">Unidades</a></li>
  <li><a href="{% url "unit_group_list" %}">Grupos de Unidades</a></li>
</ul>
{% endblock content %}

{# vim: set ft=htmldjango :#}

var_log_recetas/templates/modal_base.html
{% load crispy_forms_tags i18n %}
{% block all %}
{% if not partial %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>{{ title }}</title>
</head>
<body>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title">{{ title }}</h4>
</div>
<div class="modal-body">
  {% endif %}
  <div id="{{ id }}-container">
    {% block content %}{% endblock content %}
  </div>
  {% if not partial %}
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">{% if close_text %}{{ close_text }}{% else %}{% trans 'Close' %}{% endif %}</button>
  <button type="button" class="btn btn-primary" id="{{ id }}-ok-button" >{% if ok_text %}{{ ok_text }}{% else %}{% trans 'Ok' %}{% endif %}</button>
</div>

{% block js %}
{% endblock js %}

</body>
</html>
{% endif %}
{% endblock all %}

var_log_recetas/templates/modal_form_base.html
{% extends "modal_base.html" %}
{% load crispy_forms_tags i18n %}

{% block content %}
{% crispy form %}
{% endblock content %}

{% block js %}
<script>
setupBaseModalForm('{{ id }}');
</script>
{% endblock js %}