config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("var_log_recetas.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("ingredient/", include("var_log_recetas.ingredient.urls")),
    path("recipe/", include("var_log_recetas.recipe.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
    if "silk" in settings.INSTALLED_APPS:
        import silk.urls

        urlpatterns += [path("silk/", include(silk.urls, namespace="silk"))]

var_log_recetas/ingredient/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #     path('', views.index, name='index'),
    path("", views.IngredientListView.as_view(), name="ingredient_list"),
    path("add/", views.IngredientAddView.as_view(), name="ingredient_add"),
    path(
        "add/modal/",
        views.IngredientModalAddView.as_view(),
        name="ingredient_add_modal",
    ),
    path(
        "add/modal/submit/",
        views.IngredientModalAddView.as_view(partial=True),
        name="ingredient_add_modal_submit",
    ),
    path(
        "<int:ingredient_id>/",
        views.IngredientUpdateView.as_view(),
        name="ingredient_update",
    ),
    path("unit/", views.MeasureUnitListView.as_view(), name="unit_list"),
    path("unit/add/", views.MeasureUnitAddView.as_view(), name="unit_add"),
    path(
        "unit_group/", views.MeasureUnitGroupListView.as_view(), name="unit_group_list"
    ),
    path(
        "unit_group/add/",
        views.MeasureUnitGroupAddView.as_view(),
        name="unit_group_add",
    ),
    path(
        "unit_group/<int:unit_group_id>/",
        views.MeasureUnitGroupUpdateView.as_view(),
        name="unit_group_update",
    ),
]

var_log_recetas/recipe/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# pylint: disable=line-too-long
from __future__ import absolute_import, unicode_literals

import logging

from django.urls import path

from . import views

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name


urlpatterns = [
    path("", views.RecipeListView.as_view(), name="recipe_home"),
    path("add/", views.RecipeCreateView.as_view(), name="recipe_add"),
    path("export/", views.recipe_export_all, name="recipe_export_all"),
    path("<int:recipe_id>/", views.recipe_view, name="recipe_view"),
    path("<int:recipe_id>/edit/", views.RecipeEditView.as_view(), name="recipe_edit"),
    path(
        "<int:recipe_id>/parts/", views.RecipePartsView.as_view(), name="recipe_parts"
    ),
    path(
        "<int:recipe_id>/parts/add/",
        views.RecipeAddPartView.as_view(),
        name="recipe_parts_add",
    ),
    path("<int:recipe_id>/export/", views.recipe_export, name="recipe_export"),
    path(
        "part/<int:subrecipe_id>/",
        views.SubRecipeDetailView.as_view(),
        name="subrecipe_edit",
    ),
    path(
        "part/<int:subrecipe_id>/rename/",
        views.SubRecipeRenameView.as_view(),
        name="subrecipe_rename",
    ),
    path(
        "part/<int:subrecipe_id>/ingredient_add/",
        views.subrecipe_edit_ingredient_add,
        name="subrecipe_edit_ingredient_add",
    ),
    path(
        "part/<int:subrecipe_id>/ingredient_delete/",
        views.subrecipe_edit_ingredient_delete,
        name="subrecipe_edit_ingredient_delete",
    ),
    path(
        "part/<int:subrecipe_id>/ingredients/",
        views.subrecipe_edit_ingredients,
        name="subrecipe_edit_ingredients",
    ),
    path(
        "part/<int:subrecipe_id>/step_add/",
        views.subrecipe_edit_step_add,
        name="subrecipe_edit_step_add",
    ),
    path(
        "part/<int:subrecipe_id>/step_delete/",
        views.subrecipe_edit_step_delete,
        name="subrecipe_edit_step_delete",
    ),
    path(
        "part/<int:subrecipe_id>/step_move_up/",
        views.subrecipe_edit_step_move_up,
        name="subrecipe_edit_step_move_up",
    ),
    path(
        "part/<int:subrecipe_id>/step_move_down/",
        views.subrecipe_edit_step_move_down,
        name="subrecipe_edit_step_move_down",
    ),
    path(
        "part/<int:subrecipe_id>/steps/",
        views.subrecipe_edit_steps,
        name="subrecipe_edit_steps",
    ),
]

var_log_recetas/users/urls.py
from django.urls import path

from var_log_recetas.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

var_log_recetas/ingredient/models.py
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.


class Ingredient(models.Model):
    name = models.CharField(_("Name"), max_length=255, unique=True)
    units = models.ManyToManyField("MeasureUnit", blank=True)
    unit_groups = models.ManyToManyField("MeasureUnitGroup", blank=True)

    def has_unit(self, unit):
        return (
            self.units.filter(id=unit.id).exists()
            or self.groups.filter(units=unit).exists()
        )

    def all_units(self):
        units = set()
        units.update(self.units.all())
        for unit_group in self.unit_groups.all():
            units.update(unit_group.units.all())
        return units

    def __str__(self):
        return self.name

    class Meta(object):
        verbose_name = _("ingredient")
        verbose_name_plural = _("ingredients")

        ordering = ("name",)


class MeasureUnit(models.Model):
    name = models.CharField(_("Name"), max_length=255, unique=True)
    short_name = models.CharField(_("Short name"), max_length=255)

    def __str__(self):
        return self.name

    class Meta(object):
        verbose_name = _("measure unit")
        verbose_name_plural = _("measure units")

        ordering = ("name",)


class MeasureUnitGroup(models.Model):
    name = models.CharField(_("Nombre"), max_length=255, unique=True)
    units = models.ManyToManyField("MeasureUnit", related_name="groups")

    def __str__(self):
        return self.name

    class Meta(object):
        verbose_name = _("grupo de unidades")
        verbose_name_plural = _("grupos de unidades")

        ordering = ("name",)

var_log_recetas/recipe/models.py
from django.db import models
from django.utils.translation import ugettext as _


class MeasuredIngredient(models.Model):
    ingredient = models.ForeignKey("ingredient.Ingredient", on_delete=models.PROTECT)
    unit = models.ForeignKey("ingredient.MeasureUnit", on_delete=models.PROTECT)
    amount = models.FloatField(_("Amount"))
    subrecipe = models.ForeignKey("SubRecipe", on_delete=models.PROTECT)

    def __str__(self):
        return "{:2f} {} of {}".format(
            self.amount, self.unit.name, self.ingredient.name
        )


class Step(models.Model):
    subrecipe = models.ForeignKey("SubRecipe", on_delete=models.PROTECT)
    text = models.TextField()
    position = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        if self.position is None:
            max_position = (
                self.subrecipe.step_set.aggregate(models.Max("position"))[
                    "position__max"
                ]
                or 0
            )
            self.position = max_position + 1
        super(Step, self).save(*args, **kwargs)

    def __str__(self):
        return "Step #{} of {}: {}".format(self.position, self.subrecipe, self.text)

    class Meta:
        ordering = ("position",)


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    tags = models.ManyToManyField("Tags", blank=True)

    def as_json(self):
        output = {}
        output["title"] = self.title
        output["subrecipes"] = [sr.as_json() for sr in self.subrecipe_set.all()]
        return output

    def __str__(self):
        return self.title


class SubRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.PROTECT)
    position = models.PositiveIntegerField()
    title = models.CharField(max_length=200)

    def save(self, *args, **kwargs):
        if self.position is None:
            max_position = (
                self.recipe.subrecipe_set.aggregate(models.Max("position"))[
                    "position__max"
                ]
                or 0
            )
            self.position = max_position + 1
        super(SubRecipe, self).save(*args, **kwargs)

    def as_json(self):
        output = {}
        output["title"] = self.title
        output["ingredients"] = [
            {"amount": i.amount, "unit": i.unit.name, "ingredient": i.ingredient.name}
            for i in self.measuredingredient_set.all()
        ]
        output["steps"] = [s.text for s in self.step_set.all()]
        return output

    def __str__(self):
        return "{s.recipe} part #{s.position}: {s.title}".format(s=self)


class Tags(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return "#" + self.name

var_log_recetas/recipe/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import logging

import floppyforms.__future__ as forms
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.forms import ValidationError
from django.utils.translation import ugettext as _

from var_log_recetas.ingredient.models import Ingredient, MeasureUnit

from .models import MeasuredIngredient, Recipe, Step, SubRecipe

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name


class RecipeAddForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ("title",)

    def __init__(self, *args, **kwargs):
        super(RecipeAddForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.layout = Layout(
            "title",
            FormActions(
                Submit(
                    "submit",
                    _("Agregar"),
                    css_class="btn-primary pull-right",
                    data_loading_text=_("Agregando..."),
                ),
            ),
        )


class MeasuredIngredientForm(forms.ModelForm):
    class Meta:
        model = MeasuredIngredient
        fields = (
            "amount",
            "unit",
        )

    ingredient_name = forms.CharField(max_length=255)

    def __init__(self, *args, **kwargs):
        super(MeasuredIngredientForm, self).__init__(*args, **kwargs)
        logger.debug("initial=%s", self.initial)
        logger.debug("data: %s", self.data)
        if self.is_bound and self.data.get("ingredient_name", None):
            ingredient_name = self.data.get("ingredient_name", None)
            logger.debug("Ingredient name from instance: '%s'", ingredient_name)
        else:
            ingredient_name = self.initial.get("ingredient_name", None)
            logger.debug("Ingredient name from initial: '%s'", ingredient_name)
        if ingredient_name:
            try:
                ingredient = Ingredient.objects.get(name=ingredient_name)
                units = ingredient.all_units()
            except (Ingredient.DoesNotExist, ValueError):
                units = MeasureUnit.objects.all()
        else:
            units = MeasureUnit.objects.all()

        self.fields["amount"].widget.attrs.update(
            {"placeholder": "Amount", "min": 0.001, "step": "any"}
        )
        self.fields["ingredient_name"].widget.attrs["placeholder"] = "Ingredient"
        self.fields["ingredient_name"].empty_label = None
        self.fields["ingredient_name"].widget.datalist = [
            i.name for i in Ingredient.objects.all()
        ]
        logging.debug("Units: %s", units)
        self.fields["unit"].queryset = MeasureUnit.objects.filter(
            id__in=[u.id for u in units]
        )
        self.helper = FormHelper()
        self.helper.form_class = "form-inline"
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            "amount",
            "unit",
            "ingredient_name",
            Submit(
                "submit",
                _("Agregar"),
                css_class="btn-primary",
                data_loading_text=_("Agregando..."),
            ),
        )

    def clean_ingredient_name(self):
        name = self.cleaned_data["ingredient_name"]
        try:
            ingredient = Ingredient.objects.get(name=name)
        except Ingredient.DoesNotExist:
            raise ValidationError("Invalid ingredient")
        else:
            self.instance.ingredient = ingredient

    def clean(self):
        cleaned_data = super(MeasuredIngredientForm, self).clean()
        ingredient = cleaned_data.get("ingredient", None)
        unit = cleaned_data.get("unit", None)
        if ingredient and unit and not ingredient.has_unit(unit):
            raise forms.ValidationError(_("Unit and Ingredient do not match"))
        return cleaned_data


class StepForm(forms.ModelForm):
    class Meta:
        model = Step
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(
                attrs={"rows": 3, "cols": 140, "style": "resize: none;"}
            )
        }

    def __init__(self, *args, **kwargs):
        super(StepForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-inline"
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            "text",
            Submit(
                "submit",
                _("Agregar"),
                css_class="btn-primary",
                data_loading_text=_("Agregando..."),
            ),
        )


class SubRecipeSelectForm(forms.Form):
    def __init__(self, recipe, *args, **kwargs):
        super(SubRecipeSelectForm, self).__init__(*args, **kwargs)
        self.fields["subrecipe"] = forms.ChoiceField(
            choices=[(sr.pk, sr.title) for sr in recipe.subrecipe_set.all()],
            label=_("Parte"),
        )
        self.helper = FormHelper()
        self.helper.form_class = "form-inline"
        self.helper.form_id = "select-subrecipe-form"


class SubRecipeForm(forms.ModelForm):
    class Meta:
        model = SubRecipe
        fields = ("title",)

    def __init__(self, *args, **kwargs):
        super(SubRecipeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.layout = Layout(
            "title",
            Submit(
                "submit",
                _("Guardar"),
                css_class="btn-primary",
                data_loading_text=_("Guardando..."),
            ),
        )

var_log_recetas/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

var_log_recetas/templates/recipe/home.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Recetas" %}{% endblock title %}
{% block page_title %}{% trans "Recetas" %}{% endblock page_title %}

{% block content %}
<a class='pull-right btn btn-primary' href="{% url "recipe_add" %}">{% trans "Nueva receta" %}</a>

{% if recipes %}
<table class="table">
  <tr>
    <td>#</td>
    <td>{% trans "Título" %}</td>
  </tr>
  {% for recipe in recipes %}
  <tr>
    <td>{{ recipe.id }}</td>
    <td><a href="{% url "recipe_recipe_edit" recipe.id %}">{{ recipe.title }}</a></td>
  </tr>
  {% endfor %}
</table>
{% else %}
No hay recetas :(
{% endif %}
{% endblock content %}

{# vim: set ft=htmldjango :#}

var_log_recetas/templates/recipe/recipe_edit.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags static %}
{% block title %}{% trans "Receta" %}: {{ subrecipe.recipe.title }}{% endblock title %}
{% block page_title %}{% trans "Receta" %}: {{ subrecipe.recipe.title }}{% endblock page_title %}

{% block content %}
<h2>{% trans "Ingredientes" %}</h2>
<div id='ingredients-container'>
  <img src="{% static "img/ajax-loader.gif" %}" />
</div>
<h2>{% trans "Pasos" %}</h2>
<div id='steps-container'>
  <img src="{% static "img/ajax-loader.gif" %}" />
</div>
{% endblock content %}

{% block extra_js %}
<script>
function reloadIngredientAddForm() {
  $("#ingredient-add-container").load("{% url "recipe_recipe_edit_ingredient_add" recipe.id %}?" + $("#ingredient-add-form").serialize());
}
function reloadIngredients() {
  $("#ingredients-container").load("{% url "recipe_recipe_edit_ingredients" recipe.id %}", function(){
    $("#ingredient-add-btn").click(reloadIngredientAddForm)
 });
}

function submitIngredientAddForm() {
  $.post("{% url "recipe_recipe_edit_ingredient_add" recipe.id %}", $("#ingredient-add-form").serialize(), function(response) {
    if (response == "1") {
      reloadIngredients();
    } else {
      $("#ingredient-add-container").html(response);
      $("#id_ingredient_name").on('change', reloadIngredientAddForm)
    }
  })
}

function deleteIngredient(ingredient_id) {
  swal({
    title: "¿Seguro?",
    text: "¿Querés borrar ese ingrediente?",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: "#DD6B55",
    confirmButtonText: "Sí, borralo",
  },
  function() {
  $.getJSON("{% url "recipe_recipe_edit_ingredient_delete" recipe.id %}?ingredient_id=" + ingredient_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal borrando el ingrediente: '" + response.error + "'");
    }
    reloadIngredients();
  })
  });
}


function reloadStepAddForm() {
  $("#step-add-container").load(
    "{% url "recipe_recipe_edit_step_add" recipe.id %}?" + $("#step-add-form").serialize(),
    function (){
      $("#step-add-form").on('submit', function(e) {
        e.preventDefault();
        submitStepAddForm();
      })
    }
  );
}
function reloadSteps() {
  $("#steps-container").load("{% url "recipe_recipe_edit_steps" recipe.id %}", function(){
    $("#step-add-btn").click(reloadStepAddForm)
 });
}

function submitStepAddForm() {
  $.post("{% url "recipe_recipe_edit_step_add" recipe.id %}", $("#step-add-form").serialize(), function(response) {
    if (response == "1") {
      reloadSteps();
    } else {
      $("#step-add-container").html(response);
      $("#id_step").change(reloadStepAddForm)
    }
  })
}

function deleteStep(step_id) {
  swal({
    title: "¿Seguro?",
    text: "¿Querés borrar ese paso?",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: "#DD6B55",
    confirmButtonText: "Sí, borralo",
  },
  function() {
  $.getJSON("{% url "recipe_recipe_edit_step_delete" recipe.id %}?step_id=" + step_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal borrando el paso: '" + response.error + "'");
    }
    reloadSteps();
  })
  });
}

function moveStepUp(step_id) {
  $.getJSON("{% url "recipe_recipe_edit_step_move_up" recipe.id %}?step_id=" + step_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal moviendo el paso: '" + response.error + "'");
    }
    reloadSteps();
  });
}

function moveStepDown(step_id) {
  $.getJSON("{% url "recipe_recipe_edit_step_move_down" recipe.id %}?step_id=" + step_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal moviendo el paso: '" + response.error + "'");
    }
    reloadSteps();
  });
}

$(document).ready(function() {
  reloadIngredients();
  reloadSteps();
})

</script>
{% endblock extra_js %}
{# vim: set ft=htmldjango :#}

var_log_recetas/templates/recipe/recipe_form.html
{% extends "generic/form.html" %}
{% load i18n %}

{% block page_title %}{% trans "Agregar receta" %}{% endblock page_title %}
{% block title %}{% trans "Agregar receta" %}{% endblock title %}

{% block extra_js %}
<script language="javascript">
$(document).ready(function() {
  $('#id_title').focus();
});
</script>
{% endblock extra_js %}
{# vim: set ft=htmldjango :#}

var_log_recetas/templates/recipe/subrecipe_detail.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags static %}
{% block title %}{% trans "Receta" %}: {{ subrecipe.recipe.title }}{% endblock title %}
{% block page_title %}{% trans "Receta" %}: {{ subrecipe.recipe.title }}{% endblock page_title %}

{% block content %}
{% if subrecipe_select_form %}
{% crispy subrecipe_select_form %}
{% else %}
Parte: {{ subrecipe.title }}.
{% endif %}
<a  href="{% url "recipe_parts" subrecipe.recipe.id %}"><div class="fa fa-pencil-square-o" title="{% trans "Editar partes" %}"></div></a>
<h2>
  {% trans "Ingredientes" %}
  <a class="remote-modal" data-toggle="modal" data-target="#ingredient-create" href="{% url "ingredient_add_modal" %}" style="text-decoration: none;">
    <div class="fa fa-plus icon-add icon-h2"></div>
  </a>
</h2>
<div id='ingredients-container'>
  <img src="{% static "img/ajax-loader.gif" %}" />
</div>
<h2>
  {% trans "Pasos" %}
  <div id="step-add-btn" class="fa fa-plus icon-add icon-h2" title="{% trans "Agregar paso" %}"></div>
</h2>
<div id='steps-container'>
  <img src="{% static "img/ajax-loader.gif" %}" />
</div>
{% include "layout/modal.html" with id="ingredient-create" %}
{% endblock content %}

{% block extra_js %}
<script>
function reloadIngredientAddForm() {
  $("#ingredient-add-container").load("{% url "subrecipe_edit_ingredient_add" subrecipe.id %}?" + $("#ingredient-add-form").serialize(), function(){
    $('#id_amount').focus()
  });
}
function reloadIngredients() {
  $("#ingredients-container").load("{% url "subrecipe_edit_ingredients" subrecipe.id %}", function(){
    reloadIngredientAddForm();
 });
}

function submitIngredientAddForm() {
  $.post("{% url "subrecipe_edit_ingredient_add" subrecipe.id %}", $("#ingredient-add-form").serialize(), function(response) {
    if (response == "1") {
      reloadIngredients();
    }
  })
}

function deleteIngredient(ingredient_id) {
  swal({
    title: "¿Seguro?",
    text: "¿Querés borrar ese ingrediente?",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: "#DD6B55",
    confirmButtonText: "Sí, borralo",
  },
  function() {
  $.getJSON("{% url "subrecipe_edit_ingredient_delete" subrecipe.id %}?ingredient_id=" + ingredient_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal borrando el ingrediente: '" + response.error + "'");
    }
    reloadIngredients();
  })
  });
}


function reloadStepAddForm() {
  $("#step-add-container").load(
    "{% url "subrecipe_edit_step_add" subrecipe.id %}?" + $("#step-add-form").serialize(),
    function (){
      $("#step-add-form").on('submit', function(e) {
        e.preventDefault();
        submitStepAddForm();
      })
    }
  );
}
function reloadSteps() {
  $("#steps-container").load("{% url "subrecipe_edit_steps" subrecipe.id %}", function(){
    $("#step-add-btn").click(reloadStepAddForm)
 });
}

function submitStepAddForm() {
  $.post("{% url "subrecipe_edit_step_add" subrecipe.id %}", $("#step-add-form").serialize(), function(response) {
    if (response == "1") {
      reloadSteps();
    } else {
      $("#step-add-container").html(response);
      $("#id_step").change(reloadStepAddForm)
    }
  })
}

function deleteStep(step_id) {
  swal({
    title: "¿Seguro?",
    text: "¿Querés borrar ese paso?",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: "#DD6B55",
    confirmButtonText: "Sí, borralo",
  },
  function() {
  $.getJSON("{% url "subrecipe_edit_step_delete" subrecipe.id %}?step_id=" + step_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal borrando el paso: '" + response.error + "'");
    }
    reloadSteps();
  })
  });
}

function moveStepUp(step_id) {
  $.getJSON("{% url "subrecipe_edit_step_move_up" subrecipe.id %}?step_id=" + step_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal moviendo el paso: '" + response.error + "'");
    }
    reloadSteps();
  });
}

function moveStepDown(step_id) {
  $.getJSON("{% url "subrecipe_edit_step_move_down" subrecipe.id %}?step_id=" + step_id, function(response) {
    if (!response.success){
      swal("Ooops!", "Algo salió mal moviendo el paso: '" + response.error + "'");
    }
    reloadSteps();
  });
}



$(document).ready(function() {
  reloadIngredients();
  reloadSteps();
  $('#select-subrecipe-form').on('change', function(){
    window.location = "{% url "recipe_edit" subrecipe.recipe.id %}?" + $('#select-subrecipe-form').serialize()
  })
  $('.remote-modal').click(function () {
    $($(this).data("target") + ' .modal-content').load($(this).attr('href'));
  });
  $('#ingredient-create').on('hidden.bs.modal', function () {
    $('#id_ingredient_name').val($('#ingredient-create #id_name').val());
    reloadIngredientAddForm();
    $(this).removeData('bs.modal');
  });
})

</script>
{% endblock extra_js %}
{# vim: set ft=htmldjango :#}